In [1]:
!pip install import_ipynb

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.6 MB 5.1 MB/s 


***주의사항***  
  
이하의 Google Drive를 mount하는 코드는, nlp_main_final.ipynb 파일을 colab 환경에서 실행할 때 필요한 코드이다.  
그러나 본 파일을 colab에서 최종 확인한 후, Jupyter notebook에서 main_stream_final.ipynb 파일을 실행할 때에는 아래 코드가 작동되어서는 안 된다. Jupyter notebook에서 main_stream_final.ipynb 파일을 실행할 때, 본 파일의 predict_sentence 함수가 import되어 사용되는데, 아래 코드가 Jupyter 환경에서 오류를 발생시킬 수 있기 때문이다.  
따라서, **본 파일을 colab에서 성공적으로 완성시킨 후에는, 아래의 Drive mount 코드를 주석 처리하거나 삭제한 후에 main_stream_final.ipynb 파일을 실행하여야 한다.**

In [3]:
import import_ipynb, torch

from nlp_Preproc_final import data_to_token_ids, token_ids_to_mask
from nlp_model_final import get_model
from nlp_tokenization import KoBertTokenizer

importing Jupyter notebook from nlp_Preproc_final.ipynb
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 49.1 MB 234 kB/s 
  Attempting uninstall: graphviz
    Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 344 kB 5.0 MB/s 
  Created wheel for gluonnlp: filename=gluonnlp-0.10.0-cp37-cp37m-linux_x86_64.whl size=595726 sha256=a6eef45463fc2957def9a2e3326cbec3ee5e744608c7b0aa1d695dee3e902872
  Stored in directory: /root/.cache/pip/wheels/be/b4/06/7f3fdfaf707e6b5e98b79c041e023acffbe395d78a527eae00
Successfully built gluonnlp
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.3 MB 5.1 MB/s 
Looking in

In [4]:
# GPU 디바이스 설정
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = get_model(device, torch.cuda.is_available())

Downloading:   0%|          | 0.00/426 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/369M [00:00<?, ?B/s]

You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [7]:
def predict_sentence(input_str):
    
    # 입력받은 문장을 토큰화
    tokenizer = KoBertTokenizer.from_pretrained("monologg/kobert")
    tokenized_data = [data_to_token_ids(tokenizer, input_str)]
    attention_masks = [token_ids_to_mask(token_ids) for token_ids in tokenized_data]

    # 토큰을 텐서로 변환
    inputs_tensor = torch.tensor(tokenized_data).to(device)
    masks_tensor = torch.tensor(attention_masks).to(device)

    # 신경망의 Forward 함수 활용
    # 위의 두 텐서와 'model'의 forward 함수를 이용해서 감정에 대한 확률 벡터를 산출해보자.
    # 이때 산출된 확률 벡터를 outputs 변수로 저장하자.
    outputs = model(inputs_tensor, attention_mask=masks_tensor)

    # 위에서 산출한 감정 확률 벡터에 softmax 함수를 적용해보자
    # 이때 softmax 산출 결과를 output 변수로 저장하고 함수의 리턴하자.
    softmax = torch.nn.Softmax()
    output = softmax(outputs[0])
    
    return output

In [8]:
if __name__ == '__main__':
    while True:
        input_str = input()

    # q를 입력하면 while 루프 끝
        if input_str == "q":
            break

    # 입력받은 문장을 토큰화
    tokenizer = KoBertTokenizer.from_pretrained("monologg/kobert")
    tokenized_data = [data_to_token_ids(tokenizer, input_str)]
    attention_masks = [token_ids_to_mask(token_ids) for token_ids in tokenized_data]

    # 토큰을 텐서로 변환
    inputs_tensor = torch.tensor(tokenized_data).to(device)
    masks_tensor = torch.tensor(attention_masks).to(device)

    # 신경망의 Forward 함수 활용
    # 위의 두 텐서와 'model'의 forward 함수를 이용해서 감정에 대한 확률 벡터를 산출해보자.
    # 이때 산출된 확률 벡터를 outputs 변수로 저장하자.
    ## 여기에 코드 작성
    outputs = model(inputs_tensor, attention_mask=masks_tensor)
    # 위에서 산출한 감정 확률 벡터에 softmax 함수를 적용해보자
    # 이때 softmax 산출 결과를 output 변수로 저장하고 함수의 리턴하자.
    ## 여기에 코드 작성
    softmax = torch.nn.Softmax()
    output = softmax(outputs[0])
    print(output)
    print(predict_sentence(input_str))
    # 두 개 해서 2점

화가 난다


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


tensor([[0.0027, 0.0079, 0.9419, 0.0015, 0.0017, 0.0025, 0.0419]],
       grad_fn=<SoftmaxBackward0>)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


tensor([[0.0027, 0.0079, 0.9419, 0.0015, 0.0017, 0.0025, 0.0419]],
       grad_fn=<SoftmaxBackward0>)
혐오스럽네
tensor([[0.0020, 0.0021, 0.1103, 0.0175, 0.0101, 0.0022, 0.8558]],
       grad_fn=<SoftmaxBackward0>)
tensor([[0.0020, 0.0021, 0.1103, 0.0175, 0.0101, 0.0022, 0.8558]],
       grad_fn=<SoftmaxBackward0>)
행복하다
tensor([[7.5958e-04, 8.8955e-04, 9.1935e-04, 3.0730e-02, 3.8458e-03, 9.6205e-01,
         8.0888e-04]], grad_fn=<SoftmaxBackward0>)
tensor([[7.5958e-04, 8.8955e-04, 9.1935e-04, 3.0730e-02, 3.8458e-03, 9.6205e-01,
         8.0888e-04]], grad_fn=<SoftmaxBackward0>)
ㅂ
tensor([[0.1639, 0.6395, 0.0200, 0.1555, 0.0020, 0.0103, 0.0089]],
       grad_fn=<SoftmaxBackward0>)
tensor([[0.1639, 0.6395, 0.0200, 0.1555, 0.0020, 0.0103, 0.0089]],
       grad_fn=<SoftmaxBackward0>)
q
